global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'post_id']
  group_wait: 10s        # ждём 10с перед первой отправкой группы
  group_interval: 5m     # интервал между уведомлениями одной группы
  repeat_interval: 1h    # повтор если алерт не прошёл
  receiver: 'telegram'

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '8710539229:AAH5TUSkniqJBh92KocUceTMfGBubS4EUZ4'
        chat_id: 667953047
        message: |
          🚨 *{{ .Status | toUpper }}* — {{ .CommonLabels.alertname }}
          
          {{ range .Alerts }}
          📍 *Пост:* {{ .Labels.post_id }}
          📝 {{ .Annotations.description }}
          🕐 {{ .StartsAt.Format "15:04:05" }}
          {{ end }}
        parse_mode: 'Markdown'