global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "carwash-simulator"
    static_configs:
      - targets: ["simulator:8000"]

# Путь к файлу с правилами
rule_files:
  - /etc/prometheus/alerts.yml

# Адрес AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093